# Generated by Django 5.1.3 on 2024-12-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_orderitem_shipped_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shipped',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
    ]
