# Generated by Django 5.1.3 on 2024-12-16 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_orderitem_shipped_remove_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.shippingaddress'),
        ),
    ]
