# Generated by Django 5.1.3 on 2024-12-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_orderitem_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
