# Generated by Django 5.1 on 2024-08-14 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_product_created_at_product_is_published_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='quantity',
        ),
    ]
