# Generated by Django 5.1 on 2024-08-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='customer_rating',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='customer_review',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
