# Generated by Django 5.1 on 2024-08-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_testimonial_customer_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='customer_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='customer_review',
            new_name='review',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
    ]
