# Generated by Django 5.1 on 2024-08-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_visitorcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorcount',
            name='count',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
