# Generated by Django 5.1.3 on 2024-11-27 10:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='expiration_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailverification',
            name='otp_sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
