# Generated by Django 5.1.3 on 2024-11-28 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_emailverification_expiration_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='expiration_time',
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='otp_sent_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
