# Generated by Django 5.1.3 on 2024-11-28 09:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_remove_emailverification_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='user',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailverification',
            name='expiration_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='otp_sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
