# Generated by Django 5.1.3 on 2024-12-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_remove_emailverification_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
