# Generated by Django 5.1.3 on 2024-12-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_otptoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otptoken',
            old_name='tp_created_at',
            new_name='otp_created_at',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='e17392', max_length=6),
        ),
    ]
