# Generated by Django 5.1.3 on 2024-12-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_rename_tp_created_at_otptoken_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='066257', max_length=6),
        ),
    ]
